# Generated by Django 3.0.7 on 2020-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('profile_pic', models.ImageField(default='avatar.png', upload_to='myprofile/%d%m%y', verbose_name='Profile Picture')),
                ('gender', models.CharField(choices=[('select Gender', 'Select Gender'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=20, verbose_name='Gender')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff User')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Super User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
